# permissions for end users to edit jiras.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: jira-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: jira-aio-operator
    app.kubernetes.io/part-of: jira-aio-operator
    app.kubernetes.io/managed-by: kustomize
  name: jira-editor-role
rules:
- apiGroups:
  - app.atlassian.com
  resources:
  - jiras
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.atlassian.com
  resources:
  - jiras/status
  verbs:
  - get
