---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - app.atlassian.com
  resources:
  - jiras
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.atlassian.com
  resources:
  - jiras/finalizers
  verbs:
  - update
- apiGroups:
  - app.atlassian.com
  resources:
  - jiras/status
  verbs:
  - get
  - patch
  - update
